# Generated by Django 4.1 on 2022-12-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('telegram_id', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_perk', models.CharField(choices=[('A', 'admin user'), ('C', 'casual user'), ('M', 'master user')], max_length=1)),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BYN', 'BYN')], max_length=3)),
                ('users', models.ManyToManyField(related_name='space', through='Fin_App.Shit', to='Fin_App.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='SpandingCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fin_App.space')),
            ],
        ),
        migrations.CreateModel(
            name='Spanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BYN', 'BYN')], max_length=3)),
                ('expense', models.PositiveIntegerField()),
                ('spanding_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fin_App.spandingcategories')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fin_App.space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('action', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fin_App.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='shit',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fin_App.space'),
        ),
        migrations.AddField(
            model_name='shit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fin_App.customuser'),
        ),
        migrations.CreateModel(
            name='ReferalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('expiring_time', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fin_App.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fin_App.customuser')),
            ],
        ),
    ]
